### ISSUE TITLE
HTR-4065 is not compatible

### ISSUE THREAD

**Issue by Tirguy** [mvdwetering/ynca#17]
Hello,

I have an HTR-4065 model and i try since a long time to use it with Home Assistant that use you code...
I've try  to use also your terminal "YNCA Terminal" in order to test my configuration, but it refuse connexion and seems to say that it's not possible to connect : 

```
*** Connection lost, will attempt to reconnect on next command ***
```
So i'm not sure now that this model is compatible with YNCA !

Do you have more informations about that ? 

Note : i have the latest firmware on my HTR-4065

Bonne journée,
Thierry

**Comment by mvdwetering** [comment]
The receiver was added to the list because it is mentioned in a nodered addon as working (which uses the same protocol). https://flows.nodered.org/node/node-red-contrib-avr-yamaha

Note that the receiver only allows 1 connection using the YNCA protocol. 
Most likely something else already setup a YNCA connection to the receiver (e.g. another home automation system). I get the same message when I try to connect to my receiver while Home Assistant is already connected.

**Comment by Tirguy** [comment]
It works... I was fooled like a beginner :-D
